version: "3.8"

services:
  edata_eav:
    build: .
    env_file:
      - .env
    environment:
      RACK_ENV: development
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"

volumes:
  bundle:
